data_path: test
hash_path: prev_hash

encryption:
    type: aes
    key: raw:thisis32bitlongpassphraseimusing
    # key: file:test/key.txt
    # key: base64:dGhpc2lzMzJiaXRsb25ncGFzc3BocmFzZWltdXNpbmc=

actions:
    move_to_tmp:
        type: move
        dir: /tmp

    marcus_ftp:
        type: ftp
        user: marcus
        password: test
        host: 127.0.0.1
        dir: /backups

    anonymous_ftp:
        type: ftp
        user: anonymous
        host: 127.0.0.1
        port: 21
        dir: /upload/folder2/backups

    fail_ftp:
        type: ftp
        user: ftp
        password: ftp
        host: 127.0.0.1
        dir: /upload/folder2/backups
