.nh
.TH "BACKPACK-TEST-FORMAT" "1" "May 2022" "" ""

.SH NAME
.PP
backpack-test-format - Test format


.SH SYNOPSIS
.PP
\fBbackpack test-format [flags]\fP


.SH DESCRIPTION
.PP
Test format


.SH OPTIONS
.PP
\fB-c\fP, \fB--config\fP=""
	Path to config file.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for test-format


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	Enable debug mode. MAY PRINT SENSITIVE INFORMATION

.PP
\fB--verbose\fP[=false]
	Print more information.


.SH SEE ALSO
.PP
\fBbackpack(1)\fP
