.nh
.TH "BACKPACK-TEST-CONNECTIONS" "1" "May 2022" "" ""

.SH NAME
.PP
backpack-test-connections - Test connections


.SH SYNOPSIS
.PP
\fBbackpack test-connections [flags]\fP


.SH DESCRIPTION
.PP
Test connections


.SH OPTIONS
.PP
\fB-c\fP, \fB--config\fP=""
	Path to config file.

.PP
\fB--except\fP=[]
	List of connections to ignore.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for test-connections

.PP
\fB--only\fP=[]
	List of connections to try.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	Enable debug mode. MAY PRINT SENSITIVE INFORMATION

.PP
\fB--verbose\fP[=false]
	Print more information.


.SH SEE ALSO
.PP
\fBbackpack(1)\fP
