.nh
.TH "BACKPACK-VERSION" "1" "Apr 2022" "" ""

.SH NAME
.PP
backpack-version - Show version. backpack version 1.0-dev linux/amd64


.SH SYNOPSIS
.PP
\fBbackpack version [flags]\fP


.SH DESCRIPTION
.PP
Show version. backpack version 1.0-dev linux/amd64


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	Enable debug mode. MAY PRINT SENSITIVE INFORMATION

.PP
\fB--verbose\fP[=false]
	Print more information.


.SH SEE ALSO
.PP
\fBbackpack(1)\fP
