.nh
.TH "BACKPACK" "1" "Apr 2022" "" ""

.SH NAME
.PP
backpack - Easily backup and restore folders to and from different storages


.SH SYNOPSIS
.PP
\fBbackpack [flags]\fP


.SH DESCRIPTION
.PP
Easily backup and restore folders to and from different storages


.SH OPTIONS
.PP
\fB--debug\fP[=false]
	Enable debug mode. MAY PRINT SENSITIVE INFORMATION

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for backpack

.PP
\fB--verbose\fP[=false]
	Print more information.


.SH SEE ALSO
.PP
\fBbackpack-backup(1)\fP, \fBbackpack-restore(1)\fP, \fBbackpack-test-connections(1)\fP, \fBbackpack-version(1)\fP
