name: Clean code

on:
  push:
    branches: "**"

jobs:
  clean-code:
    name: Clean and verify code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2

      - name: Format
        shell: bash
        run: |
          output=$(gofmt -s -w -l .)

          if [ "$output" != "" ]; then
            echo "$output wasn't formatted correctly. Stopping"
            exit 1
          fi

      - name: tidy
        shell: bash
        run: |
          sum=$(sha1sum go.mod)
          go mod tidy

          if [ "$sum" != "$(sha1sum go.mod)" ]; then
            echo "go.mod wasn't tidy. Stopping"
            exit 1
          fi
